language: c

matrix:
  include:
    - os: linux
      compiler: clang
      env:
        - MATRIX_EVAL="CC=clang && CXX=clang++"

    - os: linux
      compiler: gcc
      env:
        - MATRIX_EVAL="CC=gcc && CXX=g++"

before_install:
  - eval "${MATRIX_EVAL}"

script:
  - export CPPFLAGS=-DSWDEBUG && make cleaner bint_run
  - make cleaner cov test_run

after_success:
  - bash <(curl -s https://codecov.io/bash) || echo "Codecov did not collect coverage reports"
  - make cleaner
