language: c
compiler:
  - clang
  - gcc

script:
  - export CPPFLAGS=-DSWDEBUG && make cleaner bint_run
  - make cleaner cov test_run
  - make cleaner

after_success:
  - bash <(curl -s https://codecov.io/bash) || echo "Codecov did not collect coverage reports"
