platform:
  - x86
  - Any CPU

matrix:
  fast_finish: true

# to run your custom scripts instead of automatic MSBuild
build_script:
  - set HOME=c:\cygwin\home\appveyor
  - c:\cygwin\bin\make compile
