platform:
  - x86
  - Any CPU

matrix:
  fast_finish: false

install:
  - git submodule update --init --recursive

# to run your custom scripts instead of automatic MSBuild
build_script:
  - set PATH=%PATH%;c:\cygwin\bin
  - make bin
  - make test test_runWin
  - ls -alp
  - sw_test
  - sw_test.exe
  - make test_run
  - make cleaner
